const DIRT = 103;
const DIRT_LAVA_BORDER_TOP_CORNER_EAST = 4673;
const DIRT_LAVA_BORDER_TOP_CORNER_WEST = 4674;
const DIRT_LAVA_BORDER_TOP = 4669;
const DIRT_LAVA_BORDER_EAST = 4670;
const DIRT_LAVA_BORDER_WEST = 4668;
const DIRT_LAVA_BORDER_BOTTOM_CORNER_EAST = 4672;
const DIRT_LAVA_BORDER_BOTTOM_CORNER_WEST = 4671;
const DIRT_LAVA_BORDER_SOUTH = 4667;
const DIRT_WALL_BORDER_SOUTH = 356;
const DIRT_WALL_BORDER_BOTTOM_CORNER_EAST = 364;
const DIRT_WALL_BORDER_NORTH = 357;
const DIRT_WALL_BORDER_EAST = 367;
const DIRT_WALL_BORDER_WEST = 359;
const DIRT_WALL_BORDER_BOTTOM_CORNER_WEST = 356;
const EARTH = 101;
const LAVA = [598, 599, 600, 601];
const WATER = [490, 491, 492, 493];
const VOID = 100;

module.exports = {
  DIRT,
  DIRT_LAVA_BORDER_TOP_CORNER_EAST,
  DIRT_LAVA_BORDER_TOP_CORNER_WEST,
  DIRT_LAVA_BORDER_TOP,
  DIRT_LAVA_BORDER_EAST,
  DIRT_LAVA_BORDER_WEST,
  DIRT_LAVA_BORDER_BOTTOM_CORNER_EAST,
  DIRT_LAVA_BORDER_BOTTOM_CORNER_WEST,
  DIRT_LAVA_BORDER_SOUTH,
  DIRT_WALL_BORDER_SOUTH,
  DIRT_WALL_BORDER_BOTTOM_CORNER_EAST,
  DIRT_WALL_BORDER_NORTH,
  DIRT_WALL_BORDER_EAST,
  DIRT_WALL_BORDER_WEST,
  DIRT_WALL_BORDER_BOTTOM_CORNER_WEST,
  EARTH,
  LAVA,
  WATER,
  VOID,
};
