const DIRT_TILE = 103;
const WHITE_SAND_TILE = 104;
const GRASS_TILE = 4539;
const JUNGLE_GRASS_TILE = 194;
const ROCKS_TILE = 4571;
const BROWN_SAND_TILE = 836;

module.exports = {
  DIRT_TILE,
  WHITE_SAND_TILE,
  GRASS_TILE,
  JUNGLE_GRASS_TILE,
  ROCKS_TILE,
  BROWN_SAND_TILE
};
